Lecture 2 squashed commit
Yanka0/react_course pull request #2
Opened 2024-01-25 16:57 UTC by Yanka0

2024-01-30 09:13 UTC, SArchieEdu requested changes
стоит отказаться от универсального списка тут, тк они дальше будут только мешать. Я покажу ближе к концу курса как сделать это более гибко, но сейчас лучше от этого отказаться пока

2024-01-30 09:13 UTC, SArchieEdu commented on src/App.tsx
> +type Props = OwnProps;
можно просто type Props = {}

2024-01-30 09:13 UTC, SArchieEdu commented on src/components/footer/Footer.tsx
> +      <div className={styles.wrapper}>
див скорее лишний

2024-01-30 09:13 UTC, SArchieEdu commented on src/utils/listArray/ListArray.tsx
> +}
это не лучшее решение, тк оно слишком общее и принесет больше сложностей, чем пользы. Необходимо соблюдать баланс между универсальностью и специфичностью. Меню и отзывы два по смыслу разных смысла, поэтому объединять их одним компонентом лучше не надо. Не все, что выглядит одинаково является одним компонентом, обращайте внимание на смысл и дальнейшее развитие.

2024-02-01 15:21 UTC, Yanka0 commented on src/App.tsx
> +type Props = OwnProps;
fixed, will be applied in PR #4

2024-02-01 15:21 UTC, Yanka0 commented on src/components/footer/Footer.tsx
> +      <div className={styles.wrapper}>
fixed, will be applied in PR #4

2024-02-01 15:21 UTC, Yanka0 commented on src/utils/listArray/ListArray.tsx
> +}
fixed, will be applied in PR #4

2024-02-01 15:22 UTC, Yanka0 commented
Thanks! All the fixes will be applied in PR #4

2024-02-01 15:22 UTC, merged