Lecture 3 task
Yanka0/react_course pull request #3
Opened 2024-01-29 15:01 UTC by Yanka0

2024-01-30 11:17 UTC, SArchieEdu requested changes

2024-01-30 11:17 UTC, SArchieEdu commented on src/components/restaurant/restaurantItem/RestaurantItem.tsx
> +const RestaurantItem: FunctionComponent<Props> = ({restaurant}) => {
1. про ListArray уже писал ранее.
2. Компонент сильно перегружен логикой. Ресторан знает о блюдах, хотя совсе не должен

Посмотрите разбор прошлой лекции. Рендер-пропы мы будем проходить, пока лучше стараться делать проще, а как пройдем будете использовать, знаю все нюансы

2024-01-30 11:17 UTC, SArchieEdu commented on src/components/restaurant/restaurantList/RestaurantList.tsx
> +        </div>
лучше в отдельный компонент

2024-02-01 15:30 UTC, Yanka0 commented on src/components/restaurant/restaurantItem/RestaurantItem.tsx
> +const RestaurantItem: FunctionComponent<Props> = ({restaurant}) => {
Thanks! will be applied in PR #4

2024-02-01 15:31 UTC, Yanka0 commented on src/components/restaurant/restaurantList/RestaurantList.tsx
> +        </div>
okay, will be applied in PR #4

2024-02-01 15:31 UTC, Yanka0 commented
Thanks! All the fixes will be applied in PR #4

2024-02-01 15:31 UTC, merged